Aktivitas/urls.py
from django.urls import path
from . import views

app_name = 'Aktivitas'

urlpatterns = [
    path('', views.activity, name='aktivitas'),
]

Books/urls.py
from django.urls import path
from . import views

app_name = 'Books'

urlpatterns = [
    path('', views.books, name='books'),
    path('search_books/<str:param>/', views.search_books, name='search_books'),
]

HomePage/urls.py
from django.urls import path
from . import views

app_name = 'HomePage'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_status/', views.send, name='add_status')
]

Story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HomePage.urls', namespace='HomePage')),
    path('Aktivitas/', include('Aktivitas.urls', namespace='Aktivitas')),
    path('Books/', include('Books.urls', namespace='Books')),
]

Aktivitas/models.py
from django.db import models

# Create your models here.

Books/models.py
from django.db import models

# Create your models here.

HomePage/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    status = models.CharField(max_length = 300)
    time = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return "{}".format(self.status) 

Books/forms.py
from django import forms

class inputbook (forms.Form):
    input_book = forms.CharField(min_length=1)

HomePage/forms.py
from django import forms
from .models import Status

class Status_Form(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['status']
        labels = {
            'name' : "My Status    :", 
        }
        widgets = {
            'status' : forms.TextInput(
                attrs = {
                    'class' : 'form-control',
                    'size' : 70,
                }
            ),
        }

Aktivitas/views.py
from django.shortcuts import render

# Create your views here.
def activity(request):
    return render(request,'aktivitas.html')

Books/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json
from .forms import inputbook

# Create your views here.
def books(request):
    context = {
        'form' : inputbook(),
    }
    return render(request,'books.html', context)
    # return render(request,'books.html')

def search_books(request, param):
    json = requests.get("https://www.googleapis.com/books/v1/volumes?q=" + param).json()
    return JsonResponse(json)

HomePage/views.py
from django.shortcuts import render, redirect
from .forms import Status_Form
from .models import Status

# Create your views here.
def index(request):
    response = {
        'form' : Status_Form,
        'status' : Status.objects.all(),
    }
    return render(request,'index.html', response)

def send(request):
    form = Status_Form(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            # return redirect('HomePage:index')
            return redirect('/')

    # response = {
    #     'form' : form
    # }

    # return render(request, 'index.html')

Aktivitas/templates/aktivitas.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<div style="margin-top: 10px; display: flex;">
    <div style="flex: 1; margin-right: 10px;">
        <label class="switch">
            <input type="checkbox" id="darkmode-switch">
            <span class="slider round"></span>
        </label>
    </div>
    <div style="flex: 8;">
        <span id="day-night-txt" class="text-bg-color">Day Mode</span>
    </div>
    <div style="flex: 16;"></div>
</div>

<div style="height: 30px;"></div>

<div id="accordion">
    <h3 class="accord-header">Activity</h3>
    <div class="text-bg-color">
        <p>
        -Studying at Faculty of Computer Science<br>
        -Playing games <br>
        -...
        </p>
    </div>
    <h3 class="accord-header">Organization/commitee experience</h3>
    <div class="text-bg-color">
        <p>
        -ghost member of DPM
        </p>
    </div>
    <h3 class="accord-header">Achievement</h3>
    <div class="text-bg-color">
        <p>
        -Graduated from Putra 1 elementary school with good enough score <br>
        -Graduated from Putra 1 middle school with good enough score <br>
        -Graduated from 8 high school with good enough score <br>
        -Got accepted at University of Indonesia, in Facuty of Computer Science <br>
        </p>
    </div>
</div>

{% endblock %}

Books/templates/books.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<div id="search-form" style="text-align: center; padding-top: 15px;">
    <h3>Search Books</h3>
    <div style="padding-bottom: 15px;"> <!-- Book Name : <input id="inputBook" type="text" name="inputBook" required minlength="1"></div> -->
        <form id="search-form" name="search-form" action="" method="GET">
            {% csrf_token %} {{form}}
            <br>
            <button id="submit-search" type="submit" value="submit" class="btn btn-outline-primary">Find</button>
        </form>
        <!-- <button id="submit-search" class="btn btn-outline-primary">
        </button> -->
    </div>
</div>

<!-- <div class="container-fluid body">
</div> -->

<table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Cover</th>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">More</th>
          </tr>
        </thead>
        <tbody class="body">
        </tbody>
      </table>

{% endblock %}

HomePage/templates/index.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}

    <h2 style="text-align: center; padding-bottom: 30px;">"Halo, apa kabar?"</h2>

    <div style="display: flex; justify-content: center; align-items: center; padding-bottom: 20px;">
        <form action="{% url 'HomePage:add_status' %}" method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <div style = "text-align:center; padding-top: 20px;">
                <button type="submit">Submit</button>
            </div>
        </form>
    </div>

    <div style="text-align: center">
        {% for post in status %}
        <div style="text-align: center">{{post.status}}</div>
        <div style="text-align: center">{{post.time}}</div>
        {% endfor %}
    </div>

{% endblock %}

HomePage/templates/navbar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- <link rel="stylesheet" href="/resources/demos/style.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" >
    <title>Story 6, 7, etc.</title>
</head>
<body>
    <nav id="navbar-color" class="navbar navbar-expand-lg navbar-light">
        <a id="navbar-title" class="navbar-brand" href="#">Story 6, 7, etc.</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="navbar-text nav-link" href="{% url 'HomePage:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="navbar-text nav-link" href="{% url 'Aktivitas:aktivitas' %}">Activity</a>
                </li>
                <li class="nav-item">
                    <a class="navbar-text nav-link" href="{% url 'Books:books' %}">Books</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script src="{% static 'js/jscript.js' %}"></script>
    <script src="{% static 'js/book_list.js' %}"></script>

</body>
</html>